version = 1

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "ruby"

[[analyzers]]
name = "kotlin"

  [analyzers.meta]
  runtime_version = "1.8"
  language_version = "1.7"

[[analyzers]]
name = "java"

  [analyzers.meta]
  runtime_version = "11"